version: '2'
services:
  backend:
    build: backend/
    container_name: p2d_backend
    expose:
      - "8081"
    ports:
      - "8081:8081"
    depends_on:
      - mysql
    tty: true
    links:
      - mysql
    command: ["./wait-for-it.sh", "mysql:3306"]
    command: ["python3", "manage.py", "runserver", "0.0.0.0:8081"]
  mysql:
    image: mysql:5.6
    container_name: p2d_database
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    restart: always
    ports:
      - "3304:3306"
    expose:
      - "3306"
    volumes:
      - "./mysql/db:/var/lib/mysql"
      - "./mysql/conf/my.cnf:/etc/my.cnf"
      - "./mysql/init:/docker-entrypoint-initdb.d/"
